### ISSUE TITLE
getSimInfo() returned undefined

### ISSUE THREAD

**Issue by wlisrausr** [pocesar/react-native-sim-data#1]
When I try to use this package, getSimInfo() is undefined. Any solution?

**Comment by pocesar** [comment]
do you have a sim card on the phone? if not, that's the reason
if you do, check if you have the android permission (depending on the targetSdkVersion, you need to use `PermissionsAndroid`)

**Comment by wlisrausr** [comment]
Thanks for the reply.

Yes, dual SIM card. I can get the SIM info when I try to run it in emulator but not in the real device. How can I enable the android permission?

**Comment by pocesar** [comment]
you need the `READ_PHONE_STATE` permission set in your `AndroidManifest.xml` and you can ensure that you have the permission by using 

```js
import { PermissionsAndroid } from 'react-native'

PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE)
```

**Comment by nadeem36212** [comment]
when i log RNSimData.getSimInfo().phoneNumber0 it gives me empty string......and if i log RNSimData.getSimInfo().countryName0 it logs 'pk'....can i body tell me what is the issue

**Comment by nadeem36212** [comment]
i installed permisiions in manifest.xml like this...... <uses-permission android:name="android.permission.READ_PHONE_STATE"/> and also import { PermissionsAndroid } from 'react-native' in source Code

**Comment by pocesar** [comment]
do you have anything showing in `adb logs`?

**Comment by pocesar** [comment]
well, it seems a "security feature" of Android https://stackoverflow.com/questions/23675868/how-to-get-phone-no-of-device-programmatically/23675998#23675998

**Comment by amithardikar** [comment]
thanks for reply.any other solution to detect phone number ?????

**Comment by pocesar** [comment]
you can use an SMS code as fallback (whatsapp for example uses this as first option)

**Comment by mcanikhilprajapati** [comment]
while setting up run time Permissions . and after then on success callback i try to RNSimData.getSimInfo() .  is return null .  but if before app open i set permission  its working fine , any runtime solution?

**Comment by tinydiv333** [comment]
> while setting up run time Permissions . and after then on success callback i try to RNSimData.getSimInfo() . is return null . but if before app open i set permission its working fine , any runtime solution?

Did you find any solution ? please suggest me
