### ISSUE TITLE
RNSimData.getSimInfo().phoneNumber0 from react-native-sim-data gives null

### ISSUE THREAD

**Issue by aniruddhbhamare** [pocesar/react-native-sim-data#10]
"react-native": "0.54.0", 
"react-native-sim-data": "^3.0.0"

Granted Runtime PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE, 

RNSimData.getSimInfo().phoneNumber0: null countryCode0 gives: ""

**Comment by pocesar** [comment]
same as #9

**Comment by aniruddhbhamare** [comment]
Ty,
ok I already follow the all instruction of. https://stackoverflow.com/questions/23675868/how-to-get-phone-no-of-device-programmatically/23675998#23675998

but not getting phoneNumber,

I check in Phone--> Settings --> About --> Phone Identity,  I can view the phone number in the settings, then also won't be able to get phoneNumber via this code!

**Comment by aniruddhbhamare** [comment]
another issue is ,
When first time app load RNSimData.getSimInfo().simSlotIndex0 gives undefined ,but when I reload or restart the app then I get values what might be the reason?

**Comment by pocesar** [comment]
that might be an issue during development mode for React Native, since it tries to do hot reload. restarting does affect the way the app behave

**Comment by aniruddhbhamare** [comment]
__

> Ty,
> I already follow the instruction of. https://stackoverflow.com/questions/23675868/how-to-get-phone-no-of-device-programmatically/23675998#23675998
> 
> I check in Phone--> Settings --> About --> Phone Identity, I can view the phone number in the settings, then also won't be able to get phoneNumber via this code!
> 
> but still not getting phoneNumber,

what about this one ?

> that might be an issue during development mode for React Native, since it tries to do hot reload. restarting does affect the way the app behave

Thanks!

**Comment by aniruddhbhamare** [comment]
> that might be an issue during development mode for React Native, since it tries to do hot reload. restarting does affect the way the app behave

Thanks for reply ,
I generate debug .apk file and Release .apk file ,
Still having same problem ,

When first time app load RNSimData.getSimInfo().simSlotIndex0 gives undefined ,but when I  restart the app then I get values , what might be the reason?

**Comment by aniruddhbhamare** [comment]
> Ty,
> I already follow the instruction of. https://stackoverflow.com/questions/23675868/how-to-get-phone-no-of-device-programmatically/23675998#23675998
> 
> I check in Phone--> Settings --> About --> Phone Identity, I can view the phone number in the settings, then also won't be able to get phoneNumber via this code!
> 
> but still not getting phoneNumber,

?

**Comment by juanpablogd** [comment]
+1

**Comment by tinydiv333** [comment]
> > that might be an issue during development mode for React Native, since it tries to do hot reload. restarting does affect the way the app behave
> 
> Thanks for reply ,
> I generate debug .apk file and Release .apk file ,
> Still having same problem ,
> 
> When first time app load RNSimData.getSimInfo().simSlotIndex0 gives undefined ,but when I restart the app then I get values , what might be the reason?

Did you find any solution?

**Comment by juanpablogd** [comment]
not yet

**Comment by aniruddhbhamare** [comment]
no
